
package com.example.disasterprep;

import android.os.Bundle;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

public class DisasterDetailsActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_disaster_details);

        TextView disasterTypeTextView = findViewById(R.id.disasterTypeTextView);
        TextView disasterCauseTextView = findViewById(R.id.disasterCauseTextView);

        Bundle extras = getIntent().getExtras();
        if (extras != null) {
            String category = extras.getString("category");
            String disaster = extras.getString("disaster");

            disasterTypeTextView.setText(disaster);
            disasterCauseTextView.setText(getCauseForDisaster(category, disaster));
        }
    }

    private String getCauseForDisaster(String category, String disaster) {

        if (category.equals("Geological")) {
            switch (disaster) {
                case "Earthquake":
                    return "Tectonic plate movement caused by the release of built-up energy in the Earth's crust, resulting in seismic waves that shake the ground. Earthquakes can occur along faults or fractures in the Earth's crust, and their intensity is measured using the Richter scale.";
                case "Volcano":
                    return "Volcanic eruptions occur when molten rock (magma), gases, and other materials are released from a volcanic vent. These eruptions can create ash clouds, lava flows, pyroclastic flows, and volcanic gases. Volcanic activity is often associated with the boundaries of tectonic plates.";
                case "Landslide":
                    return "Landslides are the sudden movement of rock, debris, or earth down a slope. They can be triggered by heavy rainfall, earthquakes, volcanic activity, or human actions such as deforestation or construction on unstable slopes. Landslides can cause significant damage to infrastructure and pose risks to human lives.";
                case "Avalanche":
                    return "Avalanches are rapid flows of snow, ice, and debris down a mountainside. They are typically triggered by factors such as heavy snowfall, slope instability, or human activities. Avalanches can be extremely dangerous for people engaging in winter sports or living in mountainous regions.";
                case "Sinkholes":
                    return "Sinkholes are depressions or holes that form on the Earth's surface due to the collapse of underground cavities. They can occur when soluble rocks such as limestone or gypsum dissolve, or when human activities like mining or excessive groundwater extraction weaken the supporting bedrock. Sinkholes can pose risks to structures and infrastructure.";
            }
        } else if (category.equals("Water")) {
            switch (disaster) {
                case "Flood":
                    return "Floods occur when water overflows onto normally dry land, often due to heavy rainfall, snow melt or a combination of these factors. Floods can cause widespread inundation, damage to buildings and infrastructure, and disruption of essential services. They can also result in the displacement of communities and have long-term environmental impacts.";
                case "Tsunami":
                    return "Tsunamis are series of massive ocean waves generated by undersea earthquakes, volcanic eruptions, or landslides. As these waves approach shallow water, they can grow in height and strike coastal areas with tremendous force, causing extensive destruction. Early warning systems and preparedness measures are crucial in mitigating the impact of tsunamis.";
                case "Hurricane":
                    return "Hurricanes are intense tropical cyclones with sustained winds exceeding 74 miles per hour (119 kilometers per hour). They form over warm ocean waters and can bring destructive winds, heavy rainfall, storm surges, and coastal flooding. Preparedness and evacuation plans are essential in safeguarding lives and minimizing the damage caused by hurricanes.";
                case "Limnic Eruption":
                    return "Limnic eruptions occur when a large amount of dissolved carbon dioxide is suddenly released from deep lake waters. This release displaces oxygen, creating a deadly threat to both humans and wildlife. Limnic eruptions can occur due to volcanic activity, geological processes, or changes in lake conditions, and they have the potential for catastrophic consequences.";
            }
        } else if (category.equals("Weather")) {
            switch (disaster) {
                case "Tornado":
                    return "Tornadoes are violent and rapidly rotating columns of air that form within severe thunderstorms. They are characterized by a funnel-shaped cloud extending from the storm cloud to the ground. Tornadoes can cause significant damage to structures, uproot trees, and pose severe risks to human safety. Tornadoes are often accompanied by strong winds and hail.";
                case "Blizzard":
                    return "Blizzards are severe snowstorms with strong winds, heavy snowfall, reduced visibility, and extremely cold temperatures. They can result in snowdrifts, whiteout conditions, and transportation disruptions. Blizzards can be dangerous for people caught in the storm, and they can also have significant economic impacts on affected regions.";
                case "Heatwave":
                    return "A heatwave is a prolonged period of excessively hot weather, often accompanied by high humidity and intense sunlight. Heatwaves can lead to heat-related illnesses, such as heat exhaustion and heatstroke, and they pose risks to vulnerable populations, including the elderly and individuals with pre-existing health conditions. Heatwaves can also increase the likelihood of wildfires and have detrimental effects on agriculture and ecosystems.";
                case "Drought":
                    return "Drought is an extended period of abnormally low precipitation, resulting in water scarcity and dry conditions. Droughts can have severe impacts on agriculture, water supplies, and ecosystems. They can lead to crop failures, reduced water availability, increased wildfire risk, and economic hardships for affected regions.";
                case "Wildfire":
                    return "Wildfires are uncontrolled and rapidly spreading fires that consume vegetation and forests. They are often fueled by dry conditions, high temperatures, and strong winds. Wildfires can cause extensive damage to ecosystems, destroy homes and infrastructure, and pose risks to human lives. Effective wildfire management and prevention strategies are essential in minimizing their impact.";
            }
        }

        return "";
    }

}
